# Generated by Django 5.2.7 on 2025-10-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('customer', models.CharField(blank=True, max_length=255, verbose_name='Заказчик/Контекст')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Подробная информация')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скважины/куста')),
                ('engineers', models.TextField(blank=True, verbose_name='ФИО инженеров')),
                ('current_depth', models.FloatField(default=0, verbose_name='Текущий забой (м)')),
                ('planned_depth', models.FloatField(default=0, verbose_name='Плановый забой (м)')),
                ('current_section', models.CharField(choices=[('Направление', 'Направление'), ('Кондуктор', 'Кондуктор'), ('Тех.колонна (промеж.)', 'Техническая колонна (промежуточная)'), ('Экс. колонна', 'Эксплуатационная колонна'), ('Экс. хвостовик', 'Эксплуатационный хвостовик')], default='Направление', max_length=50, verbose_name='Текущая секция')),
                ('current_operations', models.TextField(blank=True, verbose_name='Текущие работы')),
                ('has_overspending', models.BooleanField(default=False, verbose_name='Есть ли перерасход')),
                ('overspending_details', models.TextField(blank=True, null=True, verbose_name='Информация по перерасходу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NVPIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(verbose_name='Дата инцидента')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Потерянное время (текст)')),
                ('description', models.TextField(verbose_name='Описание инцидента')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvp_incidents', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Инцидент НВП',
                'verbose_name_plural': 'Инциденты НВП',
                'ordering': ['-incident_date'],
            },
        ),
    ]
