# Generated by Django 5.2.7 on 2025-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скважины/куста')),
                ('engineers', models.TextField(blank=True, verbose_name='ФИО инженеров')),
                ('current_depth', models.FloatField(default=0, verbose_name='Текущий забой (м)')),
                ('planned_depth', models.FloatField(default=0, verbose_name='Плановый забой (м)')),
                ('current_section', models.CharField(choices=[('Направление', 'Направление'), ('Кондуктор', 'Кондуктор'), ('Экс. колонна (поверх.)', 'Эксплуатационная колонна (поверхностная)'), ('Экс. колонна (промеж.)', 'Эксплуатационная колонна (промежуточная)'), ('Экс. колонна (добыча)', 'Эксплуатационная колонна (добыча)'), ('Открытый ствол', 'Открытый ствол')], default='Открытый ствол', max_length=50, verbose_name='Текущая секция')),
                ('current_operations', models.TextField(blank=True, verbose_name='Текущие работы')),
                ('has_nvp', models.BooleanField(default=False, verbose_name='Были ли НВП по нашей вине')),
                ('nvp_details', models.TextField(blank=True, null=True, verbose_name='Информация по НВП')),
                ('has_overspending', models.BooleanField(default=False, verbose_name='Есть ли перерасход')),
                ('overspending_details', models.TextField(blank=True, null=True, verbose_name='Информация по перерасходу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-updated_at'],
            },
        ),
    ]
