# Generated by Django 5.2.7 on 2025-10-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='current_section',
            field=models.CharField(choices=[('Направление', 'Направление'), ('Кондуктор', 'Кондуктор'), ('Тех.колонна (промеж.)', 'Техническая колонна (промежуточная)'), ('Экс. колонна', 'Эксплуатационная колонна'), ('Экс. хвостовик', 'Эксплуатационный хвостовик')], default='Направление', max_length=50, verbose_name='Текущая секция'),
        ),
    ]
