# Generated by Django 5.2.7 on 2025-10-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование тендера')),
                ('status', models.CharField(choices=[('PENDING', 'К загрузке'), ('TECH', 'Тех. часть загружена'), ('COMMERCIAL', 'Ком. часть загружена'), ('CONVERSATION', 'Переговоры по ком.части'), ('WON', 'Выигран'), ('LOST', 'Проигран'), ('ARCHIVED', 'В архиве')], default='PENDING', max_length=20, verbose_name='Этап')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок загрузки')),
                ('notes', models.TextField(blank=True, verbose_name='Пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-updated_at'],
            },
        ),
    ]
