# Generated by Django 5.2.7 on 2025-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_alter_well_current_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('customer', models.CharField(blank=True, max_length=255, verbose_name='Заказчик/Контекст')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['deadline'],
            },
        ),
    ]
