# Generated by Django 5.2.7 on 2025-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Объект в работе'),
        ),
    ]
