# Generated by Django 5.2.7 on 2025-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Подробная информация'),
        ),
    ]
