# Generated by Django 5.2.7 on 2025-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_well_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='last_summary_text',
            field=models.TextField(blank=True, null=True, verbose_name='Последняя сводка'),
        ),
    ]
