# Generated by Django 5.2.7 on 2025-11-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_well_last_summary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MudParameterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(auto_now_add=True, verbose_name='Время замера')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='Плотность (Пл)')),
                ('viscosity', models.FloatField(blank=True, null=True, verbose_name='Условная вязкость (УВ)')),
                ('plastic_viscosity', models.FloatField(blank=True, null=True, verbose_name='Пластическая вязкость (ПВ)')),
                ('yield_point', models.FloatField(blank=True, null=True, verbose_name='ДНС')),
                ('gel_strength_10s', models.FloatField(blank=True, null=True, verbose_name='СНС (10 сек)')),
                ('gel_strength_10m', models.FloatField(blank=True, null=True, verbose_name='СНС (10 мин)')),
                ('filtration', models.FloatField(blank=True, null=True, verbose_name='Фильтрация (Ф)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('calcium_hardness', models.FloatField(blank=True, null=True, verbose_name='Жесткость по Кальцию (Ca)')),
                ('chlorides', models.FloatField(blank=True, null=True, verbose_name='Хлориды (CL)')),
                ('potassium', models.FloatField(blank=True, null=True, verbose_name='Ионы Калия (K+)')),
                ('carbonate_content', models.FloatField(blank=True, null=True, verbose_name='Содержание карбоната кальция (Мел, CaCO3)')),
                ('phenolphthalein_alkalinity', models.FloatField(blank=True, null=True, verbose_name='Фенолфталеиновая щелочность (Pf, карбонатная щелочность)')),
                ('methyl_orange_alkalinity', models.FloatField(blank=True, null=True, verbose_name='Метилоранжевая щелочность (Mf, общая щелочность)')),
                ('lubricant', models.FloatField(blank=True, null=True, verbose_name='Смазка')),
                ('is_out_of_norm', models.BooleanField(default=False, verbose_name='Выход за пределы нормы')),
                ('raw_unparsed_params', models.TextField(blank=True, null=True, verbose_name='Неразобранные параметры')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mud_logs', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'ordering': ['-measurement_time'],
            },
        ),
    ]
