# Generated by Django 5.2.7 on 2025-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_mudparameterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudparameterlog',
            name='methylene_blue_test',
            field=models.FloatField(blank=True, null=True, verbose_name='МБТ (содержание коллоидов)'),
        ),
        migrations.AddField(
            model_name='mudparameterlog',
            name='solid_phase_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Твердая фаза (ТФ)'),
        ),
    ]
