# Generated by Django 5.2.7 on 2025-11-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0006_mudparameterlog_methylene_blue_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Название программы (например, 'Программа промывки от 20.10.2025')")),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drilling_program', to='wells.well', verbose_name='Скважина')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('Направление', 'Направление'), ('Кондуктор', 'Кондуктор'), ('Тех.колонна (промеж.)', 'Техническая колонна (промежуточная)'), ('Экс. колонна', 'Эксплуатационная колонна'), ('Экс. хвостовик', 'Эксплуатационный хвостовик')], max_length=50, verbose_name='Тип секции')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wells.drillingprogram')),
            ],
        ),
        migrations.CreateModel(
            name='DepthIntervalNorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_depth', models.FloatField(verbose_name='Начало интервала (м)')),
                ('end_depth', models.FloatField(verbose_name='Конец интервала (м)')),
                ('density_min', models.FloatField(blank=True, null=True)),
                ('density_max', models.FloatField(blank=True, null=True)),
                ('viscosity_min', models.FloatField(blank=True, null=True)),
                ('viscosity_max', models.FloatField(blank=True, null=True)),
                ('plastic_viscosity_min', models.FloatField(blank=True, null=True)),
                ('plastic_viscosity_max', models.FloatField(blank=True, null=True)),
                ('yield_point_min', models.FloatField(blank=True, null=True)),
                ('yield_point_max', models.FloatField(blank=True, null=True)),
                ('gel_strength_10s_min', models.FloatField(blank=True, null=True)),
                ('gel_strength_10s_max', models.FloatField(blank=True, null=True)),
                ('gel_strength_10m_min', models.FloatField(blank=True, null=True)),
                ('gel_strength_10m_max', models.FloatField(blank=True, null=True)),
                ('methylene_blue_test_min', models.FloatField(blank=True, null=True)),
                ('methylene_blue_test_max', models.FloatField(blank=True, null=True)),
                ('solid_phase_content_min', models.FloatField(blank=True, null=True)),
                ('solid_phase_content_max', models.FloatField(blank=True, null=True)),
                ('filtration_min', models.FloatField(blank=True, null=True)),
                ('filtration_max', models.FloatField(blank=True, null=True)),
                ('ph_min', models.FloatField(blank=True, null=True)),
                ('ph_max', models.FloatField(blank=True, null=True)),
                ('calcium_hardness_min', models.FloatField(blank=True, null=True)),
                ('calcium_hardness_max', models.FloatField(blank=True, null=True)),
                ('chlorides_min', models.FloatField(blank=True, null=True)),
                ('chlorides_max', models.FloatField(blank=True, null=True)),
                ('potassium_min', models.FloatField(blank=True, null=True)),
                ('potassium_max', models.FloatField(blank=True, null=True)),
                ('carbonate_content_min', models.FloatField(blank=True, null=True)),
                ('carbonate_content_max', models.FloatField(blank=True, null=True)),
                ('phenolphthalein_alkalinity_min', models.FloatField(blank=True, null=True)),
                ('phenolphthalein_alkalinity_max', models.FloatField(blank=True, null=True)),
                ('methyl_orange_alkalinity_min', models.FloatField(blank=True, null=True)),
                ('methyl_orange_alkalinity_max', models.FloatField(blank=True, null=True)),
                ('lubricant_min', models.FloatField(blank=True, null=True)),
                ('lubricant_max', models.FloatField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='wells.programsection')),
            ],
        ),
    ]
