# Generated by Django 5.2.7 on 2025-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_drillingprogram_programsection_depthintervalnorms'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='ID группы, куда отправлять тревоги.', null=True, verbose_name='Telegram Chat ID для оповещений'),
        ),
        migrations.AddField(
            model_name='well',
            name='telegram_topic_id',
            field=models.BigIntegerField(blank=True, help_text='ID темы (топика) внутри группы.', null=True, verbose_name='Telegram Topic ID для оповещений'),
        ),
    ]
