# Generated by Django 5.2.7 on 2025-12-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0008_well_telegram_chat_id_well_telegram_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название реагента')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Назначение')),
            ],
            options={
                'verbose_name': 'Химреагент',
                'verbose_name_plural': 'Справочник химреагентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MudType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название типа раствора')),
                ('reagents', models.ManyToManyField(blank=True, to='wells.chemicalreagent', verbose_name='Состав (химреагенты)')),
            ],
            options={
                'verbose_name': 'Тип бурового раствора',
                'verbose_name_plural': 'Справочник типов растворов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='depthintervalnorms',
            name='mud_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wells.mudtype', verbose_name='Тип раствора'),
        ),
    ]
